In [14]:
import numpy as np

In [94]:
lst = [7, 10, 23, 5, 8, 12]


# 2. Creating a diagonal matrix

In [54]:
diagonal_matrix = np.diag(lst)
print("Diagonal Matrix:")
print(diagonal_matrix)

Diagonal Matrix:
[[ 7  0  0  0  0  0]
 [ 0 10  0  0  0  0]
 [ 0  0 23  0  0  0]
 [ 0  0  0  5  0  0]
 [ 0  0  0  0  8  0]
 [ 0  0  0  0  0 12]]


# 2. Creating a 1D array (matrix)
# 2. Creating a 2D array (matrix)
# 2. Creating a 3D array (matrix)

In [138]:
one_d_array = np.array(lst)
print("\n1D Array:")
print(one_d_array)
print( one_d_array.shape)

two_d_array = np.array([[7, 10, 23], [5, 8, 12]])
print("\n2D Array:")
print(two_d_array)
print( two_d_array.shape)

three_d_array = np.array([[[7, 10, 23], [5, 8, 12], [15, 18, 20]]])
print("\n3D Array:")
print(three_d_array)
print(three_d_array.shape)


1D Array:
[ 7 10 23  5  8 12]
(6,)

2D Array:
[[ 7 10 23]
 [ 5  8 12]]
(2, 3)

3D Array:
[[[ 7 10 23]
  [ 5  8 12]
  [15 18 20]]]
(1, 3, 3)


# 3. Creating a matrix filled with random numbers from a normal distribution

In [76]:
random_matrix = np.random.randn(4, 4) 
print("\nMatrix with Random Numbers normal Distribution:")
print(random_matrix)


Matrix with Random Numbers normal Distribution:
[[-0.05958489 -1.78160205  0.21953205 -0.08911058]
 [ 0.11116932  2.05550608 -0.54853476 -0.51449947]
 [-0.06933339 -0.13632271 -0.22951163  0.30392156]
 [-1.91912737  0.16285504  0.93077277  0.18307529]]


# 4. Creating a random sample from a given array

In [85]:
random_sample = np.random.choice(lst, size=2) 
print("random sample:")
print(random_sample)

random sample:
[10 12]


# 5. Element-wise operations (addition)

In [108]:
array = np.array([7, 10, 23, 5, 8, 12])
added_array = array + 5
print(added_array)

[12 15 28 10 13 17]


# 6. Element-wise operations (multiplication)

In [114]:
multiplied_array = array * 2 
print(multiplied_array)

[14 20 46 10 16 24]


# 7. Finding the maximum value in an array

In [118]:
max_value = np.max(array)
print(max_value)

23


# 8. Finding the minimum value in an array

In [120]:
min_value = np.min(array)
print(min_value)

5


# 9. Calculating the mean of an array

In [124]:
mean_value = np.mean(array)
print(mean_value)

10.833333333333334


# 11. Flattening a 2D array

In [126]:
two_d_array = np.array([[7, 10, 23], [5, 8, 12]])
flattened_array = two_d_array.flatten()
print(flattened_array)

[ 7 10 23  5  8 12]


# 12. Rounding elements in an array

In [140]:
arr = np.array([1.23, 4.56, 7.89])
rounded_arr = np.round(arr)
print("Rounded array:", rounded_arr)

Rounded array: [1. 5. 8.]


# 13. Creating a masked array

In [192]:
arr = np.array([1, -2, 3, -4, 5])
mask = arr < 0 
masked_arr = np.ma.array(arr, mask=mask)
print("Masked array:", masked_arr)

Masked array: [1 -- 3 -- 5]


# 14. Using advanced indexing

In [172]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]  # Select specific elements
selected_elements = arr[indices]
print("Selected elements:", selected_elements)

Selected elements: [10 30 50]


# 15. Creating a random permutation of an array

In [174]:
arr = np.array([1, 2, 3, 4, 5])
permuted_arr = np.random.permutation(arr)
print("Random permutation:", permuted_arr)

Random permutation: [1 5 4 2 3]


# 16. Concatenating two arrays

In [176]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_arr = np.concatenate((arr1, arr2))
print("Concatenated array:", concatenated_arr)

Concatenated array: [1 2 3 4 5 6]


# 17. Finding unique elements in an array

In [178]:
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_elements = np.unique(arr)
print("Unique elements:", unique_elements)

Unique elements: [1 2 3 4 5]


# 18. Counting occurrences of unique elements

In [180]:
unique_elements, counts = np.unique(arr, return_counts=True)
print("Unique elements:", unique_elements)
print("Counts:", counts)

Unique elements: [1 2 3 4 5]
Counts: [1 2 1 2 1]


# 19. Creating a mask based on a condition

In [186]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3 
print("Mask:", mask)
filtered_arr = arr[mask] 
print("Filtered array:", filtered_arr)


Mask: [False False False  True  True]
Filtered array: [4 5]


# 20. Using np.where for multiple conditions

In [194]:
arr = np.array([10, 20, 30, 40, 50])
result = np.where(arr < 30, "Low", np.where(arr < 50, "Medium", "High"))
print("Result using np.where for multiple conditions:", result)

Result using np.where for multiple conditions: ['Low' 'Low' 'Medium' 'Medium' 'High']


# 21. Saving multiple arrays to NPZ file

In [196]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.savez("arrays.npz", array1=arr1, array2=arr2)
print("Arrays saved to 'arrays.npz'.")

Arrays saved to 'arrays.npz'.


# 22. Creating a random seed for reproducibility

In [198]:
np.random.seed(42)
random_numbers = np.random.rand(5)
print("Random numbers with seed 42:", random_numbers)

Random numbers with seed 42: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


# 23. Creating an array of a specific dtype

In [190]:
arr = np.array([1, 2, 3], dtype=np.float32) 
print("Array with dtype float32:", arr)
print("Data type:", arr.dtype)

Array with dtype float32: [1. 2. 3.]
Data type: float32


# 24. Performing matrix multiplication

In [200]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2) 
print("Matrix multiplication result:\n", result)

Matrix multiplication result:
 [[19 22]
 [43 50]]


# 25. Performing element-wise comparison with tolerance

In [147]:
arr1 = np.array([1.001, 2.002, 3.003])
arr2 = np.array([1.000, 2.000, 3.000])
tolerance = 0.01
comparison = np.isclose(arr1, arr2, atol=tolerance)
print("Element-wise comparison:", comparison)

Element-wise comparison: [ True  True  True]


# 26. Generating a random sample of a specified size without replacement

In [149]:
sample = np.random.choice(np.arange(10), size=5, replace=False)
print("Random sample without replacement:", sample)

Random sample without replacement: [7 5 0 8 4]


# 27. Calculating cumulative sum of elements

In [156]:
arr = np.array([1, 2, 3, 4])
cumsum = np.cumsum(arr)
print("Cumulative sum:", cumsum)

Cumulative sum: [ 1  3  6 10]


# 28. Creating a meshgrid for 2D plotting

In [158]:
x = np.linspace(-5, 5, 5)
y = np.linspace(-5, 5, 5)
X, Y = np.meshgrid(x, y)
print("Meshgrid X:\n", X)
print("Meshgrid Y:\n", Y)

Meshgrid X:
 [[-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]
 [-5.  -2.5  0.   2.5  5. ]]
Meshgrid Y:
 [[-5.  -5.  -5.  -5.  -5. ]
 [-2.5 -2.5 -2.5 -2.5 -2.5]
 [ 0.   0.   0.   0.   0. ]
 [ 2.5  2.5  2.5  2.5  2.5]
 [ 5.   5.   5.   5.   5. ]]


# 29. Using np.clip to limit values in an array

In [160]:
arr = np.array([1, 2, 3, 4, 5])
clipped_arr = np.clip(arr, 2, 4)
print("Clipped array:", clipped_arr)

Clipped array: [2 2 3 4 4]


# 30. Resizing an array

In [162]:
arr = np.array([1, 2, 3, 4, 5, 6])
resized_arr = np.resize(arr, (2, 3)) 
print("Resized array:\n", resized_arr)

Resized array:
 [[1 2 3]
 [4 5 6]]
